# Generated by Django 4.0.4 on 2022-10-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.DecimalField(decimal_places=5, max_digits=12)),
                ('visit_date', models.DateField()),
                ('num_of_pass', models.IntegerField(default=1)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NewTourDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='swipper')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TourDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='swipper')),
                ('title', models.CharField(max_length=100)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
